name: Build Distribution

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare hapi artifact
        run: |
          mkdir -p dist
          cp -R src/hapi dist/
          rm -f dist/hapi/configuration.php
          cd dist
          zip -r ../hapi.zip hapi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hapi
          path: hapi.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: hapi.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
